// 本地端口管理插件的配置、站点目录与端口冲突检查。
//
// 配置与默认站点文件放在 ~/.frpanel/plugins/port-sites/，
// 插件关掉后只停 HTTP 监听，站点配置和文件都留着，下次开启还能用。
package store

import (
	"encoding/json"
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"

	"github.com/openfrees/frp-ngrok/internal/paths"
)

// PortSite 是本插件托管的一个本机静态站。
type PortSite struct {
	Port       int    `json:"port"`
	Root       string `json:"root"`
	CustomRoot bool   `json:"customRoot"`
	// Running 是上次用户期望的运行状态，面板重启且插件仍开启时按它恢复。
	Running bool `json:"running"`
}

// PortSitesConfig 是本地端口管理插件的完整配置。
type PortSitesConfig struct {
	Enabled bool       `json:"enabled"`
	Sites   []PortSite `json:"sites"`
}

// PortSiteFile 是站点根目录里的一项。
type PortSiteFile struct {
	Name  string `json:"name"`
	Size  int64  `json:"size"`
	IsDir bool   `json:"isDir"`
}

// DefaultPortSiteRoot 返回插件为该端口准备的默认目录。
func DefaultPortSiteRoot(port int) string {
	return paths.PortSiteRoot(port)
}

// IsManagedPortSiteRoot 判断 root 是不是插件自己建的默认目录。
func IsManagedPortSiteRoot(root string, port int) bool {
	got, err := filepath.Abs(filepath.Clean(root))
	if err != nil {
		return false
	}
	want, err := filepath.Abs(DefaultPortSiteRoot(port))
	if err != nil {
		return false
	}
	return got == want
}

// DefaultDeleteFiles 给出删除弹窗「同时删除文件夹」的默认勾选。
func DefaultDeleteFiles(site PortSite) bool {
	return !site.CustomRoot && IsManagedPortSiteRoot(site.Root, site.Port)
}

// LoadPortSites 读取插件配置；文件不存在时返回空配置。
func LoadPortSites() (PortSitesConfig, error) {
	var c PortSitesConfig
	data, err := os.ReadFile(paths.PortSitesConfigFile())
	if os.IsNotExist(err) {
		return c, nil
	}
	if err != nil {
		return c, err
	}
	if len(data) == 0 {
		return c, nil
	}
	if err := json.Unmarshal(data, &c); err != nil {
		return c, fmt.Errorf("解析端口站点配置失败: %w", err)
	}
	return c, nil
}

// SavePortSites 写入插件配置。
func SavePortSites(c PortSitesConfig) error {
	if err := os.MkdirAll(paths.PortSitesDir(), 0o755); err != nil {
		return err
	}
	if c.Sites == nil {
		c.Sites = []PortSite{}
	}
	data, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return err
	}
	return writeFileAtomic(paths.PortSitesConfigFile(), append(data, '\n'), 0o600)
}

// FindPortSite 按端口查找站点。
func FindPortSite(port int) (PortSite, bool, error) {
	cfg, err := LoadPortSites()
	if err != nil {
		return PortSite{}, false, err
	}
	for _, s := range cfg.Sites {
		if s.Port == port {
			return s, true, nil
		}
	}
	return PortSite{}, false, nil
}

// CreatePortSite 登记一个站点。空 customRoot 时建默认目录并写入占位页。
func CreatePortSite(port int, customRoot string) (PortSite, error) {
	if err := CheckPortConflict(port, nil); err != nil {
		return PortSite{}, err
	}

	site := PortSite{Port: port}
	customRoot = strings.TrimSpace(customRoot)
	if customRoot == "" {
		root := DefaultPortSiteRoot(port)
		if err := os.MkdirAll(root, 0o755); err != nil {
			return PortSite{}, fmt.Errorf("创建站点目录失败: %w", err)
		}
		if err := writeDefaultIndex(root, port); err != nil {
			return PortSite{}, err
		}
		abs, err := filepath.Abs(root)
		if err != nil {
			return PortSite{}, err
		}
		site.Root = abs
		site.CustomRoot = false
	} else {
		abs, err := filepath.Abs(filepath.Clean(customRoot))
		if err != nil {
			return PortSite{}, fmt.Errorf("站点目录不合法: %w", err)
		}
		fi, err := os.Stat(abs)
		if err != nil {
			return PortSite{}, fmt.Errorf("自定义目录不存在或无法访问: %w", err)
		}
		if !fi.IsDir() {
			return PortSite{}, fmt.Errorf("自定义路径必须是文件夹")
		}
		site.Root = abs
		site.CustomRoot = true
	}

	cfg, err := LoadPortSites()
	if err != nil {
		return PortSite{}, err
	}
	cfg.Sites = append(cfg.Sites, site)
	if err := SavePortSites(cfg); err != nil {
		return PortSite{}, err
	}
	return site, nil
}

func writeDefaultIndex(root string, port int) error {
	path := filepath.Join(root, "index.html")
	if existing, err := os.ReadFile(path); err == nil && !isGeneratedPlaceholder(string(existing)) {
		return nil
	}
	return os.WriteFile(path, []byte(renderDefaultIndex(port, Locale())), 0o644)
}

func isGeneratedPlaceholder(html string) bool {
	return strings.Contains(html, "frp-ngrok:portsite-placeholder") ||
		strings.Contains(html, "这是本地端口管理插件自动生成的占位页") ||
		strings.Contains(html, "This placeholder was generated by the local port manager")
}

type placeholderCopy struct {
	Lang, Title, Live, Ready, Lead, Addr, Copy, Copied, CopyPrompt string
	Step1, Step2, Step3                                            string
}

func placeholderCopyFor(locale string) placeholderCopy {
	if locale == LocaleZH {
		return placeholderCopy{
			Lang: "zh-CN", Title: "本地站点", Live: "就绪", Ready: "站点已就绪",
			Lead: "这是本地端口管理插件自动生成的占位页。把文件放到这个目录，刷新即可看到。",
			Addr: "本机地址", Copy: "复制", Copied: "已复制", CopyPrompt: "复制地址",
			Step1: "把站点文件放进本目录", Step2: "回到浏览器刷新", Step3: "本页即被你的站点替换",
		}
	}
	return placeholderCopy{
		Lang: "en", Title: "Local site", Live: "Ready", Ready: "Site is ready",
		Lead: "This placeholder was generated by the local port manager. Drop files into this folder and refresh.",
		Addr: "Local address", Copy: "Copy", Copied: "Copied", CopyPrompt: "Copy address",
		Step1: "Put your site files in this folder", Step2: "Refresh the browser", Step3: "This page will be replaced",
	}
}

func renderDefaultIndex(port int, locale string) string {
	c := placeholderCopyFor(locale)
	repls := [][2]string{
		{"{{COPY_PROMPT}}", c.CopyPrompt},
		{"{{COPIED}}", c.Copied},
		{"{{TITLE}}", c.Title},
		{"{{READY}}", c.Ready},
		{"{{STEP1}}", c.Step1},
		{"{{STEP2}}", c.Step2},
		{"{{STEP3}}", c.Step3},
		{"{{LIVE}}", c.Live},
		{"{{LEAD}}", c.Lead},
		{"{{ADDR}}", c.Addr},
		{"{{COPY}}", c.Copy},
		{"{{LANG}}", c.Lang},
		{"{{PORT}}", strconv.Itoa(port)},
	}
	body := defaultIndexHTML
	for _, r := range repls {
		body = strings.ReplaceAll(body, r[0], r[1])
	}
	return body
}

// defaultIndexHTML 是新建默认目录时写入的单文件占位页。无外链；文案和 {{PORT}} 在写入时按创建时的界面语言填充。
const defaultIndexHTML = `<!DOCTYPE html>
<html lang="{{LANG}}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{TITLE}} · {{PORT}}</title>
<!-- frp-ngrok:portsite-placeholder -->
<style>
  :root {
    color-scheme: light;
    --bg: #f4f6f2;
    --bg-grid: rgba(23, 41, 32, 0.04);
    --surface: #ffffff;
    --text: #161a17;
    --text-dim: #545b56;
    --text-faint: #848b85;
    --signal: #0a7d4e;
    --signal-dot: #16a86a;
    --signal-soft: #e3f3ea;
    --line: #dfe3da;
    --font-ui: "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", system-ui, sans-serif;
    --font-mono: ui-monospace, "SF Mono", Menlo, "Cascadia Code", monospace;
  }
  * { box-sizing: border-box; margin: 0; }
  html, body { min-height: 100%; }
  body {
    min-height: 100dvh;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 32px 20px;
    color: var(--text);
    background-color: var(--bg);
    background-image:
      linear-gradient(var(--bg-grid) 1px, transparent 1px),
      linear-gradient(90deg, var(--bg-grid) 1px, transparent 1px);
    background-size: 32px 32px;
    font-family: var(--font-ui);
    -webkit-font-smoothing: antialiased;
  }
  .plate {
    position: relative;
    width: min(440px, 100%);
    background: var(--surface);
    border: 1px solid var(--line);
    border-radius: 9px;
    box-shadow: 0 2px 8px rgba(22, 32, 26, 0.06), 0 18px 48px rgba(22, 32, 26, 0.08);
    padding: 26px 28px 22px;
  }
  .plate::before {
    content: "";
    position: absolute;
    left: 22px; right: 22px; top: 0;
    height: 2px;
    background: var(--signal);
    border-radius: 0 0 2px 2px;
  }
  .bar {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    margin-bottom: 18px;
  }
  .live {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 4px 10px 4px 8px;
    border: 1px solid var(--line);
    border-radius: 999px;
    background: var(--surface);
    color: var(--signal);
    font-size: 12px;
    font-weight: 500;
    letter-spacing: 0.06em;
  }
  .live i {
    width: 8px; height: 8px; border-radius: 50%;
    background: var(--signal-dot);
    box-shadow: 0 0 0 3px var(--signal-soft);
    animation: pulse 1.8s ease-in-out infinite;
  }
  .brand {
    font-family: var(--font-mono);
    font-size: 11px;
    letter-spacing: 0.14em;
    color: var(--text-faint);
  }
  .readout {
    font-family: var(--font-mono);
    font-size: clamp(44px, 12vw, 64px);
    font-weight: 600;
    line-height: 1;
    letter-spacing: 0.08em;
    font-variant-numeric: tabular-nums;
    color: var(--text);
  }
  h1 {
    margin-top: 14px;
    font-size: 20px;
    font-weight: 600;
    letter-spacing: 0.02em;
  }
  .lead {
    margin-top: 10px;
    color: var(--text-dim);
    font-size: 14px;
    line-height: 1.7;
  }
  .addr {
    margin-top: 22px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    padding: 12px 12px 12px 14px;
    background: #fafbf8;
    border: 1px solid var(--line);
    border-radius: 7px;
  }
  .k {
    display: block;
    font-size: 11px;
    color: var(--text-faint);
    letter-spacing: 0.06em;
    margin-bottom: 4px;
  }
  code {
    font-family: var(--font-mono);
    font-size: 13px;
    color: var(--signal);
    word-break: break-all;
  }
  #copy {
    flex-shrink: 0;
    min-width: 72px;
    min-height: 44px;
    padding: 0 14px;
    border: 1px solid #cfe3d6;
    border-radius: 6px;
    background: var(--signal-soft);
    color: var(--signal);
    font: inherit;
    font-size: 13px;
    font-weight: 500;
    cursor: pointer;
    touch-action: manipulation;
    transition: background 0.18s ease, border-color 0.18s ease;
  }
  #copy:hover { background: #d7eee1; }
  #copy:focus-visible {
    outline: 2px solid var(--signal);
    outline-offset: 2px;
  }
  .steps {
    list-style: none;
    margin-top: 18px;
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    gap: 8px;
    padding: 0;
  }
  .steps li {
    padding: 10px 8px;
    border: 1px dashed var(--line);
    border-radius: 6px;
    color: var(--text-dim);
    font-size: 12px;
    line-height: 1.45;
    text-align: center;
  }
  .steps b {
    display: block;
    margin-bottom: 4px;
    color: var(--text);
    font-family: var(--font-mono);
    font-size: 10px;
    font-weight: 600;
    letter-spacing: 0.08em;
  }
  @media (max-width: 420px) {
    .plate { padding: 22px 18px 18px; }
    .addr { flex-direction: column; align-items: stretch; }
    .steps { grid-template-columns: 1fr; }
  }
  @keyframes pulse { 50% { opacity: 0.35; } }
  @media (prefers-reduced-motion: reduce) {
    .live i { animation: none; }
    #copy { transition: none; }
  }
</style>
</head>
<body>
<main class="plate">
  <div class="bar">
    <span class="live"><i></i>{{LIVE}}</span>
    <span class="brand">PORT SITE</span>
  </div>
  <div class="readout" aria-hidden="true">{{PORT}}</div>
  <h1>{{READY}}</h1>
  <p class="lead">{{LEAD}}</p>
  <div class="addr">
    <div>
      <span class="k">{{ADDR}}</span>
      <code id="url">http://127.0.0.1:{{PORT}}</code>
    </div>
    <button type="button" id="copy">{{COPY}}</button>
  </div>
  <ol class="steps">
    <li><b>01</b>{{STEP1}}</li>
    <li><b>02</b>{{STEP2}}</li>
    <li><b>03</b>{{STEP3}}</li>
  </ol>
</main>
<script>
(function () {
  var btn = document.getElementById("copy");
  var node = document.getElementById("url");
  if (!btn || !node) return;
  var url = node.textContent || "";
  btn.addEventListener("click", function () {
    var done = function () {
            btn.textContent = "{{COPIED}}";
            window.setTimeout(function () { btn.textContent = "{{COPY}}"; }, 1600);
          };
          if (navigator.clipboard && navigator.clipboard.writeText) {
            navigator.clipboard.writeText(url).then(done).catch(function () {
              window.prompt("{{COPY_PROMPT}}", url);
            });
          } else {
            window.prompt("{{COPY_PROMPT}}", url);
          }
  });
})();
</script>
</body>
</html>
`

// SetPortSiteRunning 记下用户期望的运行状态，供重启后恢复。
func SetPortSiteRunning(port int, running bool) error {
	cfg, err := LoadPortSites()
	if err != nil {
		return err
	}
	found := false
	for i := range cfg.Sites {
		if cfg.Sites[i].Port == port {
			cfg.Sites[i].Running = running
			found = true
			break
		}
	}
	if !found {
		return fmt.Errorf("没有端口 %d 的站点", port)
	}
	return SavePortSites(cfg)
}

// DeletePortSite 从列表移除站点；deleteFiles 为真时只删该站点根目录。
func DeletePortSite(port int, deleteFiles bool) error {
	cfg, err := LoadPortSites()
	if err != nil {
		return err
	}
	var site PortSite
	next := cfg.Sites[:0]
	found := false
	for _, s := range cfg.Sites {
		if s.Port == port {
			site = s
			found = true
			continue
		}
		next = append(next, s)
	}
	if !found {
		return fmt.Errorf("没有端口 %d 的站点", port)
	}
	cfg.Sites = next
	if err := SavePortSites(cfg); err != nil {
		return err
	}
	if !deleteFiles {
		return nil
	}
	return removeSiteRoot(site)
}

func removeSiteRoot(site PortSite) error {
	abs, err := filepath.Abs(filepath.Clean(site.Root))
	if err != nil {
		return fmt.Errorf("站点目录不合法: %w", err)
	}
	if dangerousDeleteRoot(abs) {
		return fmt.Errorf("拒绝删除这个目录：范围太大")
	}
	if !site.CustomRoot {
		want, err := filepath.Abs(DefaultPortSiteRoot(site.Port))
		if err != nil {
			return err
		}
		if abs != want {
			return fmt.Errorf("默认站点目录不匹配，拒绝删除")
		}
	}
	if err := os.RemoveAll(abs); err != nil {
		return fmt.Errorf("删除站点目录失败: %w", err)
	}
	return nil
}

func dangerousDeleteRoot(abs string) bool {
	abs = filepath.Clean(abs)
	if abs == "/" || abs == filepath.VolumeName(abs)+string(filepath.Separator) {
		return true
	}
	home, err := os.UserHomeDir()
	if err == nil && abs == filepath.Clean(home) {
		return true
	}
	for _, p := range []string{paths.AppDir(), paths.PluginsDir(), paths.DataDir(), paths.PortSitesDir()} {
		if abs == filepath.Clean(p) {
			return true
		}
	}
	return false
}

// CheckPortConflict 在创建或启动前检查端口是否可被本插件占用。
func CheckPortConflict(port int, extraReserved []int) error {
	return checkPortConflict(port, extraReserved, 0)
}

// CheckPortConflictExcept 启动已有站点时跳过「自己占用自己」。
func CheckPortConflictExcept(port int, extraReserved []int, exceptPort int) error {
	return checkPortConflict(port, extraReserved, exceptPort)
}

func checkPortConflict(port int, extraReserved []int, exceptPort int) error {
	if port <= 0 || port > 65535 {
		return fmt.Errorf("端口必须是 1-65535 的数字")
	}
	for _, reserved := range consoleListenPorts(extraReserved) {
		if port == reserved {
			return fmt.Errorf("端口 %d 是面板控制台端口，不能占用", port)
		}
	}
	cfg, err := LoadPortSites()
	if err != nil {
		return err
	}
	for _, s := range cfg.Sites {
		if s.Port == port && s.Port != exceptPort {
			return fmt.Errorf("端口 %d 已被本插件另一站点使用", port)
		}
	}
	if name, ok := tunnelLocalPortOwner(port); ok {
		if name != "" {
			return fmt.Errorf("端口 %d 已被隧道占用", port)
		}
		return fmt.Errorf("端口 %d 已被隧道占用", port)
	}
	if portListenBusy(port) {
		return fmt.Errorf("端口 %d 已被本机其他进程占用", port)
	}
	return nil
}

func consoleListenPorts(extra []int) []int {
	seen := map[int]bool{}
	var out []int
	add := func(p int) {
		if p <= 0 || seen[p] {
			return
		}
		seen[p] = true
		out = append(out, p)
	}
	add(paths.DefaultPort)
	if b, err := os.ReadFile(paths.PortFile()); err == nil {
		if n, err := strconv.Atoi(strings.TrimSpace(string(b))); err == nil {
			add(n)
		}
	}
	for _, p := range extra {
		add(p)
	}
	return out
}

func tunnelLocalPortOwner(port int) (string, bool) {
	for _, p := range LoadAllProfiles() {
		tunnels, err := LoadTunnels(p)
		if err != nil {
			continue
		}
		for _, t := range tunnels {
			if t.LocalPort == port {
				return t.Name, true
			}
		}
	}
	return "", false
}

func portListenBusy(port int) bool {
	ln, err := net.Listen("tcp", fmt.Sprintf("127.0.0.1:%d", port))
	if err != nil {
		return true
	}
	_ = ln.Close()
	return false
}

// SafeJoinSite 把相对路径接到站点根下，拒绝穿越。
func SafeJoinSite(root, name string) (string, error) {
	absRoot, err := filepath.Abs(filepath.Clean(root))
	if err != nil {
		return "", fmt.Errorf("站点目录不合法: %w", err)
	}
	name = strings.TrimSpace(name)
	if name == "" {
		return "", fmt.Errorf("文件名不能为空")
	}
	if filepath.IsAbs(name) {
		return "", fmt.Errorf("路径超出站点目录")
	}
	clean := filepath.Clean(name)
	if clean == "." || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("路径超出站点目录")
	}
	full := filepath.Join(absRoot, clean)
	rel, err := filepath.Rel(absRoot, full)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("路径超出站点目录")
	}
	return full, nil
}

// NormalizeSiteDir 把查询里的相对目录收成 / 分隔路径。空字符串表示站点根。
func NormalizeSiteDir(rel string) (string, error) {
	rel = strings.TrimSpace(strings.ReplaceAll(rel, "\\", "/"))
	rel = strings.Trim(rel, "/")
	if rel == "" || rel == "." {
		return "", nil
	}
	clean := path.Clean(rel)
	if clean == ".." || strings.HasPrefix(clean, "../") {
		return "", fmt.Errorf("路径超出站点目录")
	}
	return clean, nil
}

// SafeJoinSiteDir 把相对目录接到站点根下。空 dir 就是站点根本身。
func SafeJoinSiteDir(root, rel string) (string, error) {
	dir, err := NormalizeSiteDir(rel)
	if err != nil {
		return "", err
	}
	if dir == "" {
		abs, err := filepath.Abs(filepath.Clean(root))
		if err != nil {
			return "", fmt.Errorf("站点目录不合法: %w", err)
		}
		return abs, nil
	}
	return SafeJoinSite(root, filepath.FromSlash(dir))
}

const portSitePageMax = 200

// PaginatePortSiteFiles 按 offset/limit 切一页。limit<=0 表示从 offset 起到末尾。
func PaginatePortSiteFiles(files []PortSiteFile, offset, limit int) (page []PortSiteFile, total, off, lim int) {
	total = len(files)
	if offset < 0 {
		offset = 0
	}
	if offset > total {
		offset = total
	}
	if limit <= 0 {
		return files[offset:], total, offset, 0
	}
	if limit > portSitePageMax {
		limit = portSitePageMax
	}
	end := offset + limit
	if end > total {
		end = total
	}
	return files[offset:end], total, offset, limit
}

// ListPortSiteFiles 列出站点某个相对目录（不递归）。文件夹排在文件前面。
func ListPortSiteFiles(root, rel string) ([]PortSiteFile, string, error) {
	dir, err := NormalizeSiteDir(rel)
	if err != nil {
		return nil, "", err
	}
	abs, err := SafeJoinSiteDir(root, dir)
	if err != nil {
		return nil, "", err
	}
	fi, err := os.Stat(abs)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, "", fmt.Errorf("文件夹不存在")
		}
		return nil, "", fmt.Errorf("无法访问文件夹: %w", err)
	}
	if !fi.IsDir() {
		return nil, "", fmt.Errorf("不是文件夹")
	}
	entries, err := os.ReadDir(abs)
	if err != nil {
		return nil, "", fmt.Errorf("读取站点目录失败: %w", err)
	}
	out := make([]PortSiteFile, 0, len(entries))
	for _, e := range entries {
		info, err := e.Info()
		if err != nil {
			continue
		}
		out = append(out, PortSiteFile{
			Name:  e.Name(),
			Size:  info.Size(),
			IsDir: e.IsDir(),
		})
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].IsDir != out[j].IsDir {
			return out[i].IsDir
		}
		return strings.ToLower(out[i].Name) < strings.ToLower(out[j].Name)
	})
	return out, dir, nil
}

// DeletePortSiteFile 删除站点根下的一个文件。拒绝路径穿越，也不删目录。
func DeletePortSiteFile(root, name string) error {
	full, err := SafeJoinSite(root, name)
	if err != nil {
		return err
	}
	fi, err := os.Stat(full)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("文件不存在")
		}
		return fmt.Errorf("无法访问文件: %w", err)
	}
	if fi.IsDir() {
		return fmt.Errorf("不能删除文件夹，请用「打开文件夹」处理")
	}
	if err := os.Remove(full); err != nil {
		return fmt.Errorf("删除失败: %w", err)
	}
	return nil
}

// WritePortSiteFile 把上传内容写到指定相对目录，文件名只取最后一段。
func WritePortSiteFile(root, dir, filename string, r io.Reader) error {
	base := filepath.Base(strings.ReplaceAll(filename, "\\", "/"))
	if base == "." || base == ".." || base == string(filepath.Separator) {
		return fmt.Errorf("文件名不合法")
	}
	parent, err := SafeJoinSiteDir(root, dir)
	if err != nil {
		return err
	}
	fi, err := os.Stat(parent)
	if err != nil || !fi.IsDir() {
		return fmt.Errorf("目标文件夹不存在")
	}
	rel := base
	if clean, err := NormalizeSiteDir(dir); err == nil && clean != "" {
		rel = path.Join(clean, base)
	}
	full, err := SafeJoinSite(root, filepath.FromSlash(rel))
	if err != nil {
		return err
	}
	data, err := io.ReadAll(io.LimitReader(r, 32<<20))
	if err != nil {
		return fmt.Errorf("读取上传文件失败: %w", err)
	}
	return os.WriteFile(full, data, 0o644)
}

// OpenPortSiteFolder 用系统文件管理器打开站点里的某个相对目录。
func OpenPortSiteFolder(root, dir string) error {
	abs, err := SafeJoinSiteDir(root, dir)
	if err != nil {
		return err
	}
	fi, err := os.Stat(abs)
	if err != nil || !fi.IsDir() {
		return fmt.Errorf("站点目录不存在")
	}
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "darwin":
		cmd = exec.Command("open", abs)
	case "windows":
		cmd = exec.Command("explorer", abs)
	default:
		cmd = exec.Command("xdg-open", abs)
	}
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("无法打开文件夹: %w", err)
	}
	return nil
}
